apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nslookup db-app; do echo waiting for db; sleep 2; done']
        - name: wait-for-react
          image: busybox
          command: ['sh', '-c', 'until nslookup react-app; do echo waiting for react; sleep 2; done']
      containers:
        - name: java-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
