replicaCount: 1
image:
  repository: mysql
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3306
persistence:
  enabled: true
  size: "100Mi"
  existingClaim: false
namespace: certi-chain

#TODO move to secrets
secrets:
  database: "mydb"
  user: "user"
  password: "password"
  rootpassword: "rootpassword"