apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-db.fullname" . }}-creds
  namespace: {{ .Values.variables.namespace }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: c3lz
  {{- $secret := dict }}
  {{- if not .Release.IsInstall }}
    {{- $secret = lookup "v1" "Secret" .Values.variables.namespace (printf "%s-creds" (include "oracle-db.fullname" .)) }}
  {{- end }}
  password: {{ if and $secret (hasKey $secret.data "sysPassword") }}{{ $secret.data.sysPassword }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}
  oraclePassword: {{ if and $secret (hasKey $secret.data "sysPassword") }}{{ $secret.data.sysPassword }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}