apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-db.fullname" . }}
  namespace: {{ .Values.variables.namespace }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1521
      protocol: TCP
      name: tns
  selector:
    {{- include "oracle-db.selectorLabels" . | nindent 4 }}
